server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  datasource:
    url:  "jdbc:mysql://localhost:3306/CTDT"
    username: root
    password: root
  security:
    user:
      name: user
      password: ''

  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

jwt:
  signerKey: "PzcEXHkagVn34ElrlcOUQL/zHeIg86xNVPk5Fj94TzH0RyCLngqSyPmzUtWc7yyP"